export const videoActionTypes = {
    FETCH_VIDEOS_START: 'FETCH_VIDEOS_START',
    FETCH_VIDEOS_SUCCESS: 'FETCH_VIDEOS_SUCCESS',
    FETCH_VIDEOS_FAILURE: 'FETCH_VIDEOSs_FAILURE',

    GET_VIDEO_BY_ID_START: 'GET_VIDEO_BY_ID_START',
    GET_VIDEO_BY_ID_SUCCCESS: 'GET_VIDEO_BY_ID_SUCCCESS',
    GET_VIDEO_BY_ID_FAILURE: 'GET_VIDEO_BY_ID_FAILURE'
}