export const videoActionTypes = {
    FETCH_VIDEOS_START: 'FETCH_VIDEOS_START',
    FETCH_VIDEOS_SUCCESS: 'FETCH_VIDEOS_SUCCESS',
    FETCH_VIDEOS_FAILURE: 'FETCH_VIDEOS_FAILURE',

    GET_SUBSCRIBED_VIDEOS_SUCCESS: 'GET_SUBSCRIBED_VIDEOS_SUCCESS',

    GET_VIDEO_BY_ID_START: 'GET_VIDEO_BY_ID_START',
    GET_VIDEO_BY_ID_SUCCCESS: 'GET_VIDEO_BY_ID_SUCCCESS',
    GET_VIDEO_BY_ID_FAILURE: 'GET_VIDEO_BY_ID_FAILURE',

    GET_CHANNEL_VIDEO_START: 'GET_CHANNEL_VIDEO_START',
    GET_CHANNEL_VIDEO_SUCCESS: 'GET_CHANNEL_VIDEO_SUCCESS',
    GET_CHANNEL_VIDEO_FAILURE: 'GET_CHANNEL_VIDEO_FAILURE'
}