export const subscribeActionTypes = {
    SUBSCRIBE_START: 'SUBSCRIBE_START',
    SUBSCRIBE_SUCCESS: 'SUBSCRIBE_SUCCESS',
    SUBSCRIBE_FAILURE: 'SUBSCRIBE_FAILURE',

    GET_SUBSCRIBE_NUMBER_START: 'GET_SUBSCRIBE_NUMBER_START',
    GET_SUBSCRIBE_NUMBER_SUCCESS: 'GET_SUBSCRIBE_NUMBER_SUCCESS',
    GET_SUBSCRIBE_NUMBER_FAILURE: 'GET_SUBSCRIBE_NUMBER_FAILURE',

    CHECK_USER_SUBSCRIPTION_START: 'CHECK_USER_SUBSCRIPTION_START',
    CHECK_USER_SUBSCRIPTION_SUCCESS: 'CHECK_USER_SUBSCRIPTION_SUCCESS',
    CHECK_USER_SUBSCRIPTION_FAILURE: 'CHECK_USER_SUBSCRIPTION_FAILURE',

    UNSUBSCRIBE_START: 'UNSUBSCRIBE_START',
    UNSUBSCRIBE_SUCCESS: 'UNSUBSCRIBE_SUCCESS',
    UNSUBSCRIBE_FAILURE: 'UNSUBSCRIBE_FAILURE'
}