export const userActionTypes = {
    SAVE_USER_IN_STATE: 'SAVE_USER_IN_STATE',
    USER_LOGOUT: 'USER_LOGOUT',

    CHANNEL_VISIT_START: 'CHANNEL_VISIT_START',
    CHANNEL_VISIT_SUCCESS: 'CHANNEL_VISIT_SUCCESS',
    CHANNEL_VISIT_FAILURE: 'CHANNEL_VISIT_FAILURE'
}