export const userActionTypes = {
    USER_LOGIN_START: 'USER_LOGIN_START',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    USER_REGISTER_START: 'USER_REGISTER_START',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    SAVE_USER_IN_STATE: 'SAVE_USER_IN_STATE',
    USER_LOGOUT: 'USER_LOGOUT',

    CHANNEL_VISIT_START: 'CHANNEL_VISIT_START',
    CHANNEL_VISIT_SUCCESS: 'CHANNEL_VISIT_SUCCESS',
    CHANNEL_VISIT_FAILURE: 'CHANNEL_VISIT_FAILURE'
}