export const commentActionTypes = {
    MAKE_COMMENT_START: "MAKE_COMMENT_START",
    MAKE_COMMENT_SUCCESS: "MAKE_COMMENT_SUCCESS",
    MAKE_COMMENT_FAILURE: "MAKE_COMMENT_FAILURE",

    GET_COMMENTS_START: "GET_COMMENTS_START",
    GET_COMMENTS_SUCCESS: "GET_COMMENTS_SUCCESS",
    GET_COMMENTS_FAILURE: "GET_COMMENTS_FAILURE"
}